Separate ipv6 env test setup add
open-traffic-generator/conformance pull request #32
Opened 2022-10-21 08:18 UTC by shramroy

2022-10-25 05:58 UTC, ashutshkumr requested changes

2022-10-25 05:58 UTC, ashutshkumr commented on do.sh
> +        enable_ipv6=true
refactor as discussed over call

2023-01-04 18:29 UTC, ashutshkumr submitted a review, later dismissed

2023-01-09 12:06 UTC, Vibaswan commented
all tests passing, corrected the merge conflicts

2023-01-09 14:31 UTC, ashutshkumr approved these changes

2023-01-09 14:31 UTC, merged