adding interface tests
open-traffic-generator/conformance pull request #54
Opened 2023-01-27 15:50 UTC by Vibaswan

Fixes #53

2023-01-27 16:15 UTC, Vibaswan commented
https://github.com/open-traffic-generator/conformance/actions/runs/4026075109/jobs/6920335189


sometimes CI failing not sure whats causing the actual issue any Idea ?

2023-01-28 06:12 UTC, Vibaswan commented
fixed it was an issue with nil check

2023-01-28 16:22 UTC, ashutshkumr requested changes
The tests need to be put under `features/devices/interfaces` dir

2023-01-28 16:22 UTC, ashutshkumr commented on helpers/otg/states.go
> +			"IPv4 Addess",
*Address

2023-01-28 16:22 UTC, ashutshkumr commented on features/devices/ipv4_fowarding_test.go
> +		func() bool { return macResolutionOk(api) },
macResolutionOk -> ipv4NeighborsOk

2023-01-28 16:22 UTC, ashutshkumr commented on features/devices/ipv4_fowarding_test.go
> +func interfaceConfig(api *otg.OtgApi, tc map[string]interface{}) gosnappi.Config {
interfaceConfig -> ipv4ForwardingConfig

2023-01-28 16:22 UTC, ashutshkumr commented on features/devices/ipv4_fowarding_test.go
> +	stateInfo := api.GetIpv4State()
stateInfo -> neighbors

2023-01-28 16:22 UTC, ashutshkumr commented on features/devices/ipv4_fowarding_test.go
> +	return true
return len(neighbors) > 0

2023-01-28 16:22 UTC, ashutshkumr commented on features/devices/ipv4_fowarding_test.go
> +	}
won't be needed after suggested changes in return statement

2023-01-28 16:22 UTC, ashutshkumr commented on features/devices/test_ipv4_forwarding.py
> +
please make similar changes as in go test

2023-01-29 08:34 UTC, ashutshkumr approved these changes

2023-01-29 08:34 UTC, merged